# Generated by Django 3.1.4 on 2020-12-08 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apprenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomApp', models.CharField(max_length=100)),
                ('prenomApp', models.CharField(max_length=100)),
                ('telApp', models.CharField(max_length=20)),
                ('EmailApp', models.CharField(max_length=100)),
                ('adresseApp', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formateur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomF', models.CharField(max_length=100)),
                ('prenomF', models.CharField(max_length=100)),
                ('telF', models.CharField(max_length=20)),
                ('EmailF', models.CharField(max_length=100)),
                ('adresseF', models.CharField(max_length=100)),
                ('profesionF', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcat', models.CharField(max_length=100)),
                ('dateD', models.DateField(verbose_name='date')),
                ('DateF', models.DateField(verbose_name='date')),
                ('lieu', models.CharField(max_length=100)),
                ('montant', models.IntegerField()),
                ('idFormateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.formateur')),
                ('idcategorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.categorie')),
            ],
        ),
        migrations.CreateModel(
            name='suivre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heure', models.CharField(max_length=100)),
                ('idApp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.apprenant')),
                ('idFormation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog2.formation')),
            ],
        ),
    ]
