# Generated by Django 3.1.4 on 2020-12-10 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog2', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='formation',
            name='Apprenant',
            field=models.ManyToManyField(to='blog2.Apprenant'),
        ),
        migrations.AlterField(
            model_name='apprenant',
            name='EmailApp',
            field=models.EmailField(max_length=100),
        ),
        migrations.AlterField(
            model_name='formateur',
            name='EmailF',
            field=models.EmailField(max_length=100),
        ),
        migrations.DeleteModel(
            name='suivre',
        ),
    ]
